[package]
org = "ballerinax"
name = "h2.driver"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["H2"]
repository = "https://github.com/ballerina-platform/module-ballerinax-h2.driver"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "./lib/h2-@h2.driver.version@.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "h2.driver-native"
version = "@toml.version@"
path = "../native/build/libs/h2.driver-native-@project.version@.jar"
